run:
  timeout: 5m

issues:
  exclude-dirs:
    - benchmark

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
